trigger:
  branches:
    include:
      - main
      
pool:
  vmImage: 'ubuntu-latest'
  
steps:
  - script: echo 'Starting Docker Build and Compose'
    displayName: 'Starting Docker Build and Compose'
  
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'
    
  - task: Docker@2
    displayName: 'Push Docker Image to Registry'
    inputs:
      command: 'push'
      tags: 'latest'
      containerRegistry: cb459485-d77a-48ec-8ac6-fafba772f942
  
  - task: Docker@2
    displayName: 'Docker Compose Up'
    inputs:
      command: 'composeUp'
      dockerComposeFile: '**/docker-compose.yml'
      removeContainersOnPull:
